[package]
name = "rpncalc"
version = "0.1.0"
authors = ["peaceandwhisky <pioneerandf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
clap = "3.0.0-beta.1"
thiserror = "1.0.25"
